# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20160211_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_en', models.CharField(blank=True, max_length=255, null=True)),
                ('category_es', models.CharField(blank=True, max_length=255, null=True)),
                ('category_pt', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
