# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usercategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('category_en', 'category_es', 'category_pt')]),
        ),
    ]
