# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160213_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('category_en', 'category_es', 'category_pt')]),
        ),
    ]
